name: CI

on: [push]

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Format
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: format
      - name: Lint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint
