name: CI

on: [push]

jobs:
  server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build test image
        working-directory: ./server
        run: docker build . --tag search-service-test:$(date +%m) --target test
      - name: Run tests
        working-directory: ./server
        run: docker run -p 5000:5000 search-service-test:$(date +%m)
